### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by talismax** [GaProgMan/OwaspHeaders.Core#21]
![image](https://user-images.githubusercontent.com/2261681/37800098-c9fc44ca-2def-11e8-842f-51c9996fad3c.png)

**Comment by GaProgMan** [comment]
Whoops. Marked as 'good first issue' for anyone who wants to make a start in OSS development.

**Comment by GaProgMan** [comment]
I'll leave this open for someone in the OSS community to solve, and add the "Help Wanted" tag in order to attract attention.

This feels like a super easy change for someone new to OSS to make.

## Potential Fix

Line [33 of XFrameOptionsConfiguration.cs](https://github.com/GaProgMan/OwaspHeaders.Core/blob/master/src/Models/XFrameOptionsConfiguration.cs#L33) currently reads:

    stringBuilder.Append("SOMEORIGIN");

This should be changed to:

    stringBuilder.Append("SAMEORIGIN");
